### ISSUE TITLE
Condition always true

### ISSUE THREAD

**Issue by jjakubassa** [shashankskagnihotri/cospgd#1]
Hi! I suppose the `or` should be an `and`. This way, the `else` branch will never be reached. 

https://github.com/shashankskagnihotri/cospgd/blob/c024843cf463341a380e7901d7c7d80ab8f6a4e7/unet_backbones/attack.py#L228

Kind regards.

**Comment by shashankskagnihotri** [comment]
Yes, I have now removed the if-else condition. Thanks :)
