### ISSUE TITLE
the file you have requested does not exist.

### ISSUE THREAD

**Issue by C-c-candy** [shashankskagnihotri/cospgd#2]
Hello author，
When I download the pretrained model in GoogleDrive Link it occurs "Sorry, the file you have requested does not exist.

Make sure that you have the correct URL and the file exists."If it's convenient, could you please send it again?

**Comment by shashankskagnihotri** [comment]
Thank you for bringing this to my notice. I have now updated the link with the file to download. 

Best Regards
Shashank

**Comment by C-c-candy** [comment]
I also wanna ask how can I visualize the results of image segmentation?
I'm looking forward to your reply!
Thank you!
Candy

**Comment by shashankskagnihotri** [comment]
Hi, I have not explicitly enabled visualizations in this code.
However, doing so is very easy, in file [trainer.py](https://github.com/shashankskagnihotri/cospgd/blob/main/unet_backbones/backbones_unet/utils/trainer.py), the 'pred' is the output of the model.
You can use the visualization tools provided by the original author of the repository to save these predictions as .png files.

**Comment by C-c-candy** [comment]
Thank you sooooooooo much!
But I would like to visualize the images after the attack. Is it possible to save the post-attack images as PNG files in the attack.py? Additionally, after reviewing the pretrained-backbones-unet, I did not find  related visualization code. Could you please provide further guidance? Thank you very much!

**Comment by shashankskagnihotri** [comment]
The original maker of the repository had provided the code in [visualizer.py](https://github.com/shashankskagnihotri/cospgd/blob/main/unet_backbones/utils/visualizer.py).

Sure, you can save the post attack images, you would simply have to add lines to save an image for the variable 'images' after [this line](https://github.com/shashankskagnihotri/cospgd/blob/f2780a812ebc35d3ef71ad587d3b484367561cc9/unet_backbones/backbones_unet/utils/trainer.py#L293C40-L293C46).
Since, these images are not normalized (as the model normalizes them), you do not even need to perform any denormalization on these images. They can directly be saved using simple torchvision functions, [as example here](https://discuss.pytorch.org/t/how-to-save-image/48808/4).

**Comment by C-c-candy** [comment]
With your help, I have been able to resolve the previous issues. However, when I run the attack.py file, it jumps to unet.py at encoder = create_model( and an exception occurs: 
An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7b28b8ce9280>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /timm/convnext_tiny.in12k_ft_in1k/resolve/main/pytorch_model.bin (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7b28b8ce9280>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

requests.exceptions.ConnectionError: (MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /timm/convnext_tiny.in12k_ft_in1k/resolve/main/pytorch_model.bin (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7b28b8ce9280>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"), '(Request ID: 3f36d24a-ac77-4d20-8a0d-727e4f43c312)')

The above exception was the direct cause of the following exception:

  File "/home/gpu-pc/Documents/LX/cospgd-main/unet_backbones/backbones_unet/model/unet.py", line 118, in __init__
    encoder = create_model(
  File "/home/gpu-pc/Documents/LX/cospgd-main/unet_backbones/train.py", line 209, in main
    model = Unet(
  File "/home/gpu-pc/Documents/LX/cospgd-main/unet_backbones/train.py", line 269, in <module>
    main(args_)
huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.)
If convenient, I would like to ask if there is a link where I can download this model and save it locally? Thank you for your help.

**Comment by shashankskagnihotri** [comment]
Hi, depending on the model you want to use, I guess you can directly download the model from huggingface and give a path instead of using the internet to download the model.

I would refer you to the huggingface docs for more help regading this.

**Comment by C-c-candy** [comment]
Thank you for your patient response. I added import os and os.environ["HF_ENDPOINT"] = "https://hf-mirror.com" in front of unet.py, which resolved the issue, and I hope this can help others. However, I encountered a new problem where the current model's structure does not match the structure of the pre-trained model, specifically showing inconsistencies in the parameter dimensions of some layers. Therefore, I would like to ask which encoder is used in the provided pre-trained model?

**Comment by shashankskagnihotri** [comment]
Great, it is a convnext_tiny encoder used with the --small_decoder flag. The mismatch must be in the decoder.

**Comment by C-c-candy** [comment]
Thank you!
I would also like to ask if you have reproduced SegPGD? Because I have seen comparative experiments in your paper, so I would like to inquire how you reproduced it. I only found a single .py file on GitHub.This has been bothering me for a long time.

**Comment by shashankskagnihotri** [comment]
Hi, the code for using SegPGD can be found [here](https://github.com/shashankskagnihotri/cospgd/blob/acdbf0049f07ce4c8b7dac19f05d71191e1af8e3/unet_backbones/backbones_unet/utils/trainer.py#L257) 

I highly appreciate your enthusiasm regarding the work and the field, however, I would strongly suggest to go over the repository in detail once, as to the best of my knowledge it is quite comprehensive.
